[package]
name = "kateb"
version = "2.0.2"
edition = "2024"
authors = ["Kiavash Mazi <kiavash@gmail.com>"]
description = "A CLI font installer for installing Farsi free fonts"
license = "GPL-3.0-or-later"
repository = "https://github.com/kiamazi/kateb"
homepage = "https://github.com/kiamazi/kateb"
documentation = "https://github.com/kiamazi/kateb#readme"
keywords = ["cli", "font", "installer", "farsi", "persian"]
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
clap = { version = "4.6.7", features = ["derive"] }
dirs = "7.0.0"
indicatif = "0.18.6"
nix = { version = "0.31.3", features = ["user"] }
rayon = "1.12.0"
regex = "1.13.1"
reqwest = { version = "0.13.5", features = ["blocking", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tempfile = "3.27.0"
toml = "0.8"
toml_edit = "0.25.15"
zip = "8.6.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
