[[fonts]]
name = "gandom"
api = "https://api.github.com/repos/rastikerdar/gandom-font/releases"
repo_name = "gandom-font"
repo_url = "https://github.com/rastikerdar/gandom-font/"
publisher_name = "Saber Rastikerdar"
publisher_url = "https://github.com/rastikerdar"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "nahid"
api = "https://api.github.com/repos/rastikerdar/nahid-font/releases"
repo_name = "nahid-font"
repo_url = "https://github.com/rastikerdar/nahid-font/"
publisher_name = "Saber Rastikerdar"
publisher_url = "https://github.com/rastikerdar"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "parastoo"
api = "https://api.github.com/repos/rastikerdar/parastoo-font/releases"
repo_name = "parastoo-font"
repo_url = "https://github.com/rastikerdar/parastoo-font/"
publisher_name = "Saber Rastikerdar"
publisher_url = "https://github.com/rastikerdar"
direct_download = ""
extract_regex = "^web/([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "sahel"
api = "https://api.github.com/repos/rastikerdar/sahel-font/releases"
repo_name = "sahel-font"
repo_url = "https://github.com/rastikerdar/sahel-font/"
publisher_name = "Saber Rastikerdar"
publisher_url = "https://github.com/rastikerdar"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "shabnam"
api = "https://api.github.com/repos/rastikerdar/shabnam-font/releases"
repo_name = "shabnam-font"
repo_url = "https://github.com/rastikerdar/shabnam-font/"
publisher_name = "Saber Rastikerdar"
publisher_url = "https://github.com/rastikerdar"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "samim"
api = "https://api.github.com/repos/rastikerdar/samim-font/releases"
repo_name = "samim-font"
repo_url = "https://github.com/rastikerdar/samin-font/"
publisher_name = "Saber Rastikerdar"
publisher_url = "https://github.com/rastikerdar"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "tanha"
api = "https://api.github.com/repos/rastikerdar/tanha-font/releases"
repo_name = "tanha-font"
repo_url = "https://github.com/rastikerdar/tanha-font/"
publisher_name = "Saber Rastikerdar"
publisher_url = "https://github.com/rastikerdar"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "vazir"
api = "https://api.github.com/repos/rastikerdar/vazirmatn/releases"
repo_name = "vazirmatn"
repo_url = "https://github.com/rastikerdar/vazirmatn/"
publisher_name = "Saber Rastikerdar"
publisher_url = "https://github.com/rastikerdar"
direct_download = ""
extract_regex = "^fonts/ttf/([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "vazircode"
api = "https://api.github.com/repos/rastikerdar/vazir-code-font/releases"
repo_name = "vazir-code-font"
repo_url = "https://github.com/rastikerdar/vazir-code-font/"
publisher_name = "Saber Rastikerdar"
publisher_url = "https://github.com/rastikerdar"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "ziracode"
api = "https://api.github.com/repos/kiamazi/zira-code-font/releases"
repo_name = "zira-code-font"
repo_url = "https://github.com/kiamazi/zira-code-font/"
publisher_name = "Kiavash Mazi"
publisher_url = "https://github.com/kiamazi"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "estedad"
api = "https://api.github.com/repos/aminabedi68/Estedad/releases"
repo_name = "Estedad"
repo_url = "https://github.com/aminabedi68/Estedad/"
publisher_name = "Amin Abedi"
publisher_url = "https://github.com/aminabedi68"
direct_download = ""
extract_regex = "^Statics/ttf/([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "mikhak"
api = "https://api.github.com/repos/aminabedi68/Mikhak/releases"
repo_name = "Mikhak"
repo_url = "https://github.com/aminabedi68/Mikhak/"
publisher_name = "Amin Abedi"
publisher_url = "https://github.com/aminabedi68"
direct_download = ""
extract_regex = "^ttf/([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "behdad"
api = "https://api.github.com/repos/font-store/BehdadFont/releases"
repo_name = "BehdadFont"
repo_url = "https://github.com/font-store/BehdadFont/"
publisher_name = "Saleh Souzanchi"
publisher_url = "https://github.com/font-store"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "farbod"
api = "https://api.github.com/repos/font-store/FarbodFont/releases"
repo_name = "FarbodFont"
repo_url = "https://github.com/font-store/FarbodFont/"
publisher_name = "Saleh Souzanchi"
publisher_url = "https://github.com/font-store"
direct_download = ""
extract_regex = "^([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "ganjnameh"
api = "https://api.github.com/repos/font-store/GanjnamehFont/releases"
repo_name = "GanjnamehFont"
repo_url = "https://github.com/font-store/GanjnamehFont/"
publisher_name = "Saleh Souzanchi"
publisher_url = "https://github.com/font-store"
direct_download = ""
extract_regex = "^fonts/([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "nastaliq"
api = "https://api.github.com/repos/font-store/font-IranNastaliq/releases"
repo_name = "font-IranNastaliq"
repo_url = "https://github.com/font-store/font-IranNastaliq/"
publisher_name = "Saleh Souzanchi"
publisher_url = "https://github.com/font-store"
direct_download = "https://github.com/font-store/font-IranNastaliq/raw/master/WebFonts/IranNastaliq-Web.ttf"
extract_regex = ""
asset_number = 0

[[fonts]]
name = "nika"
api = "https://api.github.com/repos/font-store/NikaFont/releases"
repo_name = "NikaFont"
repo_url = "https://github.com/font-store/NikaFont/"
publisher_name = "Saleh Souzanchi"
publisher_url = "https://github.com/font-store"
direct_download = ""
extract_regex = "^fonts/([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "shahab"
api = "https://api.github.com/repos/font-store/ShahabFont/releases"
repo_name = "ShahabFont"
repo_url = "https://github.com/font-store/ShahabFont/"
publisher_name = "Saleh Souzanchi"
publisher_url = "https://github.com/font-store"
direct_download = ""
extract_regex = "^fonts/([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "pfont"
api = "https://api.github.com/repos/pfont/pfont/releases"
repo_name = "pfont"
repo_url = "https://github.com/pfont/pfont/"
publisher_name = "Persian Free Font"
publisher_url = "https://github.com/pfont"
direct_download = ""
extract_regex = "^pfont/ttf/Hinted/([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "lalezar"
api = "https://api.github.com/repos/BornaIz/Lalezar/releases"
repo_name = "Lalezar"
repo_url = "https://github.com/BornaIz/Lalezar/"
publisher_name = "Borna Izadpanah"
publisher_url = "https://github.com/BornaIz"
direct_download = "https://raw.githubusercontent.com/BornaIz/Lalezar/master/fonts/Lalezar-Regular.ttf"
extract_regex = ""
asset_number = 0

[[fonts]]
name = "arad"
api = "https://api.github.com/repos/MohamadDarvishi/Arad/releases"
repo_name = "Arad"
repo_url = "https://github.com/MohamadDarvishi/Arad"
publisher_name = "Mohammad Darvishi"
publisher_url = "https://github.com/MohamadDarvishi"
direct_download = ""
extract_regex = "^MainFonts.*/Static_TTF/([^/]+\\.ttf)$"
asset_number = 1

[[fonts]]
name = "ario"
api = "https://api.github.com/repos/MohamadDarvishi/Ario/releases"
repo_name = "Ario"
repo_url = "https://github.com/MohamadDarvishi/Ario"
publisher_name = "Mohammad Darvishi"
publisher_url = "https://github.com/MohamadDarvishi"
direct_download = ""
extract_regex = "^Main_Fonts/([^/]+\\.ttf)$"
asset_number = 0

[[fonts]]
name = "rooyin"
api = "https://api.github.com/repos/MohamadDarvishi/Rooyin/releases"
repo_name = "Rooyin"
repo_url = "https://github.com/MohamadDarvishi/Rooyin"
publisher_name = "Mohammad Darvishi"
publisher_url = "https://github.com/MohamadDarvishi"
direct_download = ""
extract_regex = "^Font Family/([^/]+\\.ttf)$"
asset_number = 0
